<?php

/**
 * Created by PhpStorm.
 * User: Laurin
 * Date: 28.07.2018
 * Time: 11:42
 */
class StoryPointBoard extends Board
{

  public function parse($template = "defaultStoryPoint.php")
  {
    return parent::parse($template); // TODO: Change the autogenerated stub
  }

}